In [2]:
import pandas as pd

In [7]:
df = pd.read_csv("광주광역시_광산구_음식물_스티커.csv", encoding='cp949')

In [8]:
df

,연번,사업장명,주소,위도,경도,데이터기준일자
0,1,하남공단종합상사,광주광역시 광산구 하남산단4번로 172 (장덕동 992-11),35.190699,126.809015,2024-04-30
1,2,알리바이(24시편의점),"광주광역시 광산구 왕버들로 11, 가동 101호 (장덕동 505-86)",35.202587,126.811926,2024-04-30
2,3,주)에스엠마트남동,"광주광역시 광산구 장덕로95번길 46 (장덕동 1102, 수완자이아파트 정문)",35.197635,126.819853,2024-04-30
3,4,씨유하남8번로점,"광주광역시 광산구 하남산단천변우로 28, 1층 (도천동 622-2)",35.208658,126.813457,2024-04-30
4,5,미니스톱하남도천점,광주광역시 광산구 하남산단8번로 169 기업은행 옆,35.209141,126.814229,2024-04-30
...,...,...,...,...,...,...
689,690,지에스25 수완아울렛점,"광주광역시 광산구 풍영로 200번길 81, 1층",35.189859,126.818727,2024-04-30
690,691,지에스25 수완아울렛점,"광주광역시 광산구 광산구 풍영로 200번길 81, 1층",35.189859,126.818727,2024-04-30
691,692,지에스25 도산빌리지점,광주광역시 광산구 광산구 송도로182번길 15-3,35.130522,126.794948,2024-04-30
692,693,하남마트,광주광역시 광산구 광산구 무진대로231번길 29-13(우산동 1577-3),35.163426,126.805293,2024-04-30
693,694,씨유 첨단호반1차점,"광주광역시 광산구 광산구 월계로 117-35, 상가동 101~1012호",35.216085,126.837418,2024-04-30